channels:
  - conda-forge

dependencies:
  - boto3
  - hvac
  - ipykernel
  - ipywidgets
  - nbclient
  - nbformat
  - numpy
  - pandas
  - dill
  - pmdarima
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - pip:
    - nowcast-lstm
