# Next forecast

```{r}
#| label: fig-pred-ppi1
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_1, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi2
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_2, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi3
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_3, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi4
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_4, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi5
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_5, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi6
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_6, store = "store_ppi")
```

```{r}
#| label: fig-pred-ppi7
#| fig-cap: test
#| fig-width: 8.5
#| fig-height: 5
targets::tar_read(plot_preds_ppi_7, store = "store_ppi")
```
